name: Deploy

on:
  push: main
  pull_request: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v2
          with:
            distribution: goreleaser
            version: latest
            args: release --rm-dist
